# Generated by Django 3.1.4 on 2020-12-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last name')),
                ('birthday', models.DateTimeField(verbose_name='Birthday')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('state', models.CharField(max_length=200, verbose_name='State')),
                ('city', models.CharField(max_length=200, verbose_name='City')),
                ('phone', models.IntegerField(verbose_name='Phone number')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
            },
        ),
    ]
